# https://taskfile.dev

version: "3"

tasks:
  dev:
    desc: Start the development server
    cmds:
      - pnpm run dev
  build:
    cmds:
      - pnpm build

  preview:
    cmds:
      - pnpm preview
