name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Vite Github Pages Deployer
        # You may pin to the exact commit or the version.
        # uses: skywarth/vite-github-pages-deployer@ec2e9a434804544a618cf2e0ffd9fc41ddf0b50c
        uses: skywarth/vite-github-pages-deployer@v1.5.0
        with:
          # Public base path string for vite, this affects the routing, history and asset links. Make sure to provide appropriately since Github Pages stores your app in a directory under a subdomain.
          public_base_path: /covert-grizzly/
          # Which folder do you want your Github Page to use as root directory. Usually it is your build output directory such as ./dist
          build_path: ./dist
          # Node env that will be used for the installation of dependencies. It is imperative you use an environment that has 'vite' as dependency. Commonly, that is 'dev'.
          install_phase_node_env: dev
          # Node env that will be used for build phase.
          build_phase_node_env: production
          # Your preference of package manager: 'npm' and 'yarn' are possible values.
          package_manager: pnpm
          # Desired name for the Deployment environment. It is also the exposed artifact name which contains the build output (dist).
          artifact_name: github-pages
          # Controls the debug mode, boolean, true is for on. When turned on, it'll output certain information on certain steps. Mainly used for development, but use it as you please to inspect your env and variables.
          debug_mode: false
          # Controls the working directory for both install and build steps
          working_path: ./